"""add property_type to listings

Revision ID: 2ee06cadc93f
Revises: 80d004653c92
Create Date: 2026-03-04 19:33:41.748584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2ee06cadc93f'
down_revision: Union[str, None] = '80d004653c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('property_type', sa.String(length=50), server_default='unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'property_type')
    # ### end Alembic commands ###
