"""initial_schema

Revision ID: 80d004653c92
Revises: 
Create Date: 2026-03-04 18:28:09.508948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80d004653c92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('availability_schedule', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=10), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=False),
    sa.Column('price_trend', sa.Float(), nullable=False),
    sa.Column('availability_score', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_prices_travel_date'), 'flight_prices', ['travel_date'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('square_meters', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('is_customer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_external_id'), 'listings', ['external_id'], unique=True)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('total_listings', sa.Integer(), nullable=False),
    sa.Column('available_listings', sa.Integer(), nullable=False),
    sa.Column('median_price', sa.Float(), nullable=False),
    sa.Column('avg_occupancy_rate', sa.Float(), nullable=False),
    sa.Column('booking_velocity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_date'), 'market_snapshots', ['date'], unique=False)
    op.create_table('search_demand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_term', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('search_interest_index', sa.Float(), nullable=False),
    sa.Column('search_interest_trend', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_demand_date'), 'search_demand', ['date'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('rain_probability', sa.Float(), nullable=False),
    sa.Column('snow_probability', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stay_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('temperature_forecast', sa.Float(), nullable=False),
    sa.Column('temperature_trend', sa.Float(), nullable=False),
    sa.Column('snowfall_next_3_days', sa.Float(), nullable=False),
    sa.Column('snowfall_next_7_days', sa.Float(), nullable=False),
    sa.Column('sun_hours_forecast', sa.Float(), nullable=False),
    sa.Column('cloud_cover_forecast', sa.Float(), nullable=False),
    sa.Column('rain_probability', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('snow_depth', sa.Float(), nullable=False),
    sa.Column('fresh_snow', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecasts_stay_date'), 'weather_forecasts', ['stay_date'], unique=False)
    op.create_table('availability_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_snapshots_listing_id'), 'availability_snapshots', ['listing_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_listing_id'), 'bookings', ['listing_id'], unique=False)
    op.create_table('cleaning_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('assigned_cleaner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assigned_cleaner_id'], ['cleaners.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_prices_listing_id'), 'competitor_prices', ['listing_id'], unique=False)
    op.create_table('property_cleaners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('cleaner_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cleaner_id'], ['cleaners.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_cleaners')
    op.drop_index(op.f('ix_competitor_prices_listing_id'), table_name='competitor_prices')
    op.drop_table('competitor_prices')
    op.drop_table('cleaning_tasks')
    op.drop_index(op.f('ix_bookings_listing_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_availability_snapshots_listing_id'), table_name='availability_snapshots')
    op.drop_table('availability_snapshots')
    op.drop_index(op.f('ix_weather_forecasts_stay_date'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_table('weather')
    op.drop_index(op.f('ix_search_demand_date'), table_name='search_demand')
    op.drop_table('search_demand')
    op.drop_index(op.f('ix_market_snapshots_date'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_listings_external_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_flight_prices_travel_date'), table_name='flight_prices')
    op.drop_table('flight_prices')
    op.drop_table('events')
    op.drop_table('cleaners')
    # ### end Alembic commands ###
